


thesaurus_function <- function(joined_ID_DE){
  
  # joined_keywords <- names(which(base::colSums(joined_ID_DE[,-(which(colnames(joined_ID_DE) == "AU"))]) >= 2)) # 1. select columns with sum >1; 2. get their names
  # joined_keywords1 <- names(which(base::colSums(joined_ID_DE[,-(which(colnames(joined_ID_DE) == "AU"))]) >= 1))
  # joined_keywords1[which(!(joined_keywords1 %in% joined_keywords))]
  
  # !!!! 
  #   "BRONZE-AGE"
  # !!!!
  
  meta_categories <- list(
    
    # ### Geography
    #   
    #"eurasia"
    Europe = c("DARTMOOR","EURASIA","RENNE","UNITED KINGDOM", "GARGAS CAVE","ROUFFIGNAC CAVE","FUMANE CAVE","CUEVA MORIN","GROTTE XVI","GROTTE DU RENNE",
               "BALTIC",	"EASTERN-CENTRAL-EUROPE",	"BELGIUM","BRNO","PARIS BASIN","BISTRITA BASIN","ROMANIA","BADEN-WURTTEMBERG","PORTUGAL","VERONA","CATALONIA",
               "VENETO","LOWER SAXONY","GIBRALTAR","RUEIL-MALMAISON","AQUITAINE","BRITTANY","ANTOLINAKO KOBA","CRETE",	"SOUTHERN SCANDINAVIA","WESTERN-EUROPE","SOVIET UNION",
               "IBERIAN MEDITERRANEAN REGION","SOUTHWESTERN FRANCE","NORTHERN IBERIA","JIHOMORAVSKY","CAPELLADES","DORDOGNE","SWABIAN ALB","NETHERLANDS","EASTERN CARPATHIANS",
               "SOUTH-EAST EUROPE","CANTABRIA","SCHONINGEN","MEDITERRANEAN","EL CASTILLO","CARPATHIANS","SWABIAN JURA","ALICANTE [COMUNIDAD VALENCIA]","CZECH REPUBLIC","EL-CASTILLO",
                "SAINT-CESAIRE","LOS HUESOS","MIDDLE DANUBE","SOUTHERN CAUCASIA","ATAPUERCA","COMUNIDAD VALENCIA","CENTRAL EUROPE","FRANCE","IBERIAN PENINSULA","SPAIN",
                "ITALY","MEDITERRANEAN REGION","EUROPE","PREHISTORIC EUROPE","WESTERN EUROPE","GERMANY","SIERRA DE ATAPUERCA","GIRONDE","SOUTHERN EUROPE","CENTRAL-EUROPE",
                "IRELAND","SCANDINAVIA","WALES","SOUTHERN ENGLAND","KRAPINA","ANCIENT MEDITERRANEAN AND NEAR EAST","EASTERN BOHEMIA","BULGARIA","GREECE","TENAGHI PHILIPPON",
                "IBERIA","IRISH MEGALITHS","IRISH AGRICULTURAL CONDITIONS","ROMAN EMPIRE"),
    
    # central and northern asia
    Central_Northern_Asia = c("DEAD SEA",	"CENTRAL-ASIA","CAUCASUS","STEPPE","SIBERIA","ENISEI RIVER VALLEY","WEST ANATOLIA","ANATOLIA","MESOPOTAMIA","CENTRAL ASIA"),
    
    # east-asia
    East_Asia = c("KOREA","CHINA","BOSE BASIN","NORTHERN CHINA","ASIA", "SRI LANKA","RURAL BANGLADESH","EAST ASIA","SOUTHEAST ASIA","PREHISTORIC THAILAND","EAST-ASIA","SOUTH ASIAN TRIANGLE",
                  "JOMON", "JAPAN","TIBET","EAST TIMOR","HOABINHIAN","FLORES","GUANGXI","FENGSHUDAO"), 
    
    Australia_Tasmania = c("NEW-SOUTH-WALES","NORTHERN AUSTRALIA","AUSTRALIAN STONE TOOLS","TASMANIA"),
    
    Oceania_Polynesia = c("PAPUA-NEW-GUINEA","WEST POLYNESIA","SAMOA","TUTUILA ISLAND","TONGA","TONGAN","TONGAN MARITIME EMPIRE","LAPITA","NEW-GUINEA",
                "POLYNESIA","MICRONESIANS","EASTER ISLAND","RAPA NUI","RAPA","NUI","MARQUESAS ISLANDS","MARAE","AITUTAKI",
                "FIJIAN VILLAGES","LAPITA SETTLEMENT"),
    
    # levante, near and middle east
    Near_Middle_East = c( "EBA SOUTHERN LEVANT",	"LEVANT","GESHER BENOT YA'AQOV","GESHER BENOT YAAQOV", "GESHER-BENOT-YAAQOV", "ISRAEL","QAFZEH CAVE" ,"HAYONIM CAVE","QESEM","QESEM CAVE","TABUN CAVE","EL-WAD TERRACE","CARMEL CAVES","MIDDLE EAST",
                         "IRAN","ZAGROS","WARWASI","ZAGROS MOUNTAINS","YAFTEH","NEAR-EAST","SOUTHERN LEVANT","ANCIENT MEDITERRANEAN AND NEAR EAST",
                         "SOUTH-EASTERN ARABIA", "OMAN","DHOFAR","EASTERN ANATOLIA",	"WADI SURDUD"),
    
    # africa
    Africa = c("POST-HOWIESONS POORT","HOWIESONS-POORT LAYERS",	"ELANDS BAY CAVE",	"STILL BAY INDUSTRY",	"NORTH-AFRICA",	"CENTRAL SUDAN","BORDER CAVE","EGYPT","GONA","NILE VALLEY","JEBEL IRHOUD","AFRICA", "AFRICAN ARCHAEOLOGY","SUDAN","FAZZAN BASIN","FTEAH CAVE CYRENAICA","KLASIES RIVER","WEST TURKANA","ETHIOPIA",
               "SOUTH AFRICA","EAST AFRICAN RIFT","SOUTH-AFRICA","WESTERN CAPE","EAST AFRICA","NAMIBIA","SOUTHERN-AFRICA","DIEPKLOOF ROCK SHELTER" ,
               "ETHIOPIAN RIFT","BLOMBOS CAVE","DIE KELDERS","WEST AFRICA","SUB-SAHARAN AFRICA",
               "BLOMBOS", "SIBUDU", "KLASIES", "DIEPKLOOF", "OLDUVAI-GORGE","OLDUVAI GORGE","WONDERWERK CAVE","LAKE NDUTU","LOKALALEI 2C","22 ZINJANTHROPUS","MOSSEL BAY",
               "KOOBI-FORA", "LAKE TURKANA","DIEPKLOOF ROCK", "SOUTHERN AFRICA","MADAGASCAR","DUINEFONTEIN 2","NORTHERN CAPE","KATHU PAN 1","STILL BAY","HOWIESONS","POORT","WESTERN CAPE PROVINCE"),
    
    # meso-south america
    Meso_South_America = c("CLASSIC MAYA","SOUTH AMERICA PEOPLING","CLASSIC-MAYA",
                           "MAYA LOWLANDS","AZTEC HUMAN SACRIFICE","NORTHERN URUGUAY","CARIBBEAN",	"ANDES", "ATACAMA DESERT", "CHIHUAHUA", "MEXICO", "OAXACA",	"CENTRAL ANDES","ANTOFAGASTA",
                           "ALERO CUEVAS SITE","BRAZILIAN","BRAZILIAN ARCHAEOLOGY","AMERICA","PRE-COLUMBIAN CARIBBEAN","QUEBRADA TACAHUAY","UCAYALI","RIO NEGRO","MATIAS GULF","SOUTH-CENTRAL ANDES"),
    
    # north america
    North_America = toupper(c("PALEOINDIAN POINTS","LATE PREHISTORIC US",	"CLOVIS POINTS",	"DAISY CAVE","california","GREAT BASIN",	 "american southwest", "us", "USA","great plains","US SOUTHWEST",
                              "GREAT-BASIN","COASTAL SOUTHERN CALIFORNIA","SAN-FRANCISCO-BAY","SAN-FRANCISCO BAY" ,"NORTH AMERICA",
                              "EMERYVILLE SHELLMOUND","NORTH-AMERICA","FOLSOM","PACIFIC-NORTHWEST","PACIFIC NORTHWEST","BRITISH-COLUMBIA","KEATLEY CREEK","LILLOOET","TEXAS","SOUTHERN HIGH-PLAINS",
                              "COAST SALISH","SALISH","SALISH SEA","AMERICA", "SOUTHEASTERN UNITED-STATES","WESTERN GREAT-BASIN","NORTH AMERICAN ARCTIC","MESA VERDE (CO)",
                              "PUEBLO SOCIETIES","PUEBLO SOCIETY","PUEBLO","ANCESTRAL PUEBLO",
                              "KEATLEY","CLOVIS","NORTH-AMERICAN ARCHAEOLOGY",	"L. FRIEDKIN SITE","UNITED-STATES", "ARCTIC CANADA","LATE WOODLAND","ALASKA","PALEO CROSSING 33ME274",
                              "CALIFORNIA PREHISTORY",	"CANADA IMPLICATIONS","WOODLAND CERAMICS","OHIO",	"FRANCISCO BAY", "GREAT-SALT-LAKE")),
    
    Arctic = c("SMALL TOOL TRADITION","ALASKA PREHISTORY","PALEOESKIMO DEMOGRAPHY","ARCTIC SMALL TOOL TRADITION","GREENLAND",	"ARCTIC CANADA",	"ALASKA", "BERINGIA",	"EASTERN BERINGIA"),
    
    Islands = c("ISLAND","ISLANDS","INTER-ISLAND CONTACT","PACIFIC","SOCIETY ISLANDS","CHANNEL-ISLANDS","AITUTAKI"),
    
    Maritime_Lacustrine_Riverine = c("LAKE","SEA-LEVEL",	"SEA-LEVEL HISTORY","SEA","NORTH COAST","RIVER MAIN SITE","FLUVIAL TERRACE","RIVER TERRACE","MARITIME REGION","MARITIME",
                                     "RIVER VALLEY", "COAST","MARITIME NETWORKS","LAKE LEVEL","RIVER"),
    

    
    # caves
    Cave = c("ELANDS BAY CAVE",	"TABUN CAVE", "GARGAS CAVE","ROUFFIGNAC CAVE","FUMANE CAVE","CUEVA MORIN","GROTTE XVI","GROTTE DU RENNE","WONDERWERK CAVE",
             "BLOMBOS CAVE","KLASIES RIVER","DIE KELDERS","FTEAH CAVE CYRENAICA","SHELTER","SIBUDU CAVE","QESEM CAVE","QAFZEH CAVE","HAYONIM CAVE","KELDERS CAVE 1",
             "BORDER CAVE",	"DAISY CAVE","FTEAH CAVE CYRENAICA","TABUN CAVE","GROTTE","CAVES","CAVE","EL-CASTILLO","ROCK-SHELTER","GARGAS CAVE","CARMEL CAVES","ROUFFIGNAC CAVE","CUEVA MORIN"),
    
    
    
    # Stone tools/technology
    Lithic_Tools_Technology = c("BLADES","MICROLITHIC","LAMINAR ASSEMBLAGE","BLADE/BLADELET TECHNOLOGY","BLADE TECHNOLOGY","BIPOLAR KNAPPING","STONE KNAPPING","BLADE PRODUCTION","LEVALLOIS TECHNOLOGY" ,"FLINT KNAPPING",
                          "PRODUCTION SKILL","MACROLITHIC TOOLS","MACROBLADE","NEOCORTEX SIZE","FLAKE SCAR PATTERNS","BIPOLAR REDUCTION","FLAKING","PERCUSSION FLAKING","LITHICS","CORE TECHNOLOGIES",
                          "UNIFACIAL STONE TOOLS","GEOMETRIC MICROLITHS","AUSTRALIAN STONE TOOLS","TECHNOLOGY","LITHIC","TOOLS","LITHIC TECHNOLOGY","STONE TOOL","STONE TOOLS","STONE ARTIFACTS","LITHIC FRAGMENT","TECHNOLOGIES","STONE TECHNOLOGY" ,"INDUSTRIES","INDUSTRY","ASSEMBLAGES",
                          "STONES","STONE ARTIFACT ASSEMBLAGES","STONE","TOOLMAKING",	"HANDAXES",	"FLAKES",
                          "KNAPPING QUALITY",	"KNIVES","FLAKE-BASED LITHIC TOOLS",	"COMPLEX KNAPPING","BLADE","KNAPPING",
                          "TECHNOLOGICAL DEVELOPMENT","TRANSITIONAL TECHNO-COMPLEXES","KNAPPING COSTS","ORIGIN OF MICROBLADE TECHNOLOGY","POTATO KNAPPING",
                          "BIFACE","BIFACE INDEX",
                          "LARGE CUTTING TOOLS","LITHIC ASSEMBLAGES","LITHIC TECHNOLOGICAL VARIABILITY","LITHIC TYPOLOGY","MICROBLADES",	"STILL BAY INDUSTRY",	
                          "MODE 2",	"SMALL TOOL TRADITION", "ARCTIC SMALL TOOL TRADITION","TOOL CURATION","TOOL STONES",	
                          "TOOL","TOOL PRODUCTION","TOOL-MAKING","REDUCTION SEQUENCES",	"BLADELETS/MICROLITHS",
                          "LITHIC ANALYSIS","REFITTING","CHAINE OPERATOIRE","CHANE OPRATOIRE","OPERATIONAL SEQUENCES","LITHIC TAPHONOMY","SEQUENTIAL LITHIC INFORMATION ANALYSIS","LITHIC STUDIES",
                          "DEBITAGE"),
    
    Handaxes = c("HANDAXES",	"LEVALLOIS","LEVALLOIS METHOD","LEVALLOIS TECHNOLOGY","LEVALLOIS METHODS","HANDAXE","ACHEULEAN HANDAXES","ACHEULEAN HANDAXE","HANDAXE SYMMETRY"),
    
    Projectile_Points = c("PROJECTILE TECHNOLOGY","STEMMED POINTS","PROJECTILE","PROJECTILE-POINT MORPHOLOGY","LITHIC PROJECTILE POINTS",
                          "PROJECTILES",	"PROJECTILE-POINT TECHNOLOGY","ARROW-POINT TYPES","DART-POINT TYPES","CLOVIS POINTS","DART","BOW","BOW AND ARROW","ATLATL AND DART","CLOVIS POINT",
                          "POINT TYPES","ARROW","LEAF POINTS","PROJECTILE-POINT TYPES", "PROJECTILE POINT TYPOLOGY","DART-ARROW INDEX" ,"HAFTED",  
                         "HAFTED PROJECTILE POINTS","PROJECTILE POINT","ARROW POINTS","DART POINTS","FLUTED PROJECTILE POINTS","FLUTED POINTS", "BIFACIAL STEMMED POINTS",
                         "PROJECTILE POINTS","ARROW HEAD","POINT TECHNOLOGY","PALEOINDIAN PROJECTILE POINTS"),
    
    Lithic_Raw_Material = c("LITHIC SOURCE AREAS","OBSIDIAN PROCUREMENT",	"RAW-MATERIAL SELECTIVITY","RAW-MATERIAL AVAILABILITY","RAW-MATERIAL QUALITY",
                            "RAW MATERIALS","ALLOCHTHONOUS MATERIALS","OBSIDIAN","VOLCANIC GLASS","BURNT FLINTS","RAW-MATERIAL","FLINT"),
    
    
    Material_culture = c("ARTIFACTS","MATERIAL CULTURE PROXIES","BEADS","ARTIFACT","MATERIAL CULTURE"),
    
    
    Ceramics = c("TECHNOLOGICAL-CHOICES-IN-CERAMIC-PRODUCTION",	"CERAMIC CONSUMPTION",	"INDIGENOUS CERAMICS",	"ORIGINS OF POTTERY","MESOLITHIC POTTERY",	"ANCIENT CERAMICS",	
                 "POTTERY DESCRIPTION","POTTERY-MAKING TECHNIQUES","EARLY CERAMICS",
                 "EARLY FORMATIVE POTTERY",	"EARLY POTTERY","WOODLAND CERAMICS",	"AMPHORA WORKSHOPS","CERAMIC TECHNOLOGY","CERAMIC PRODUCTION","BROWNWARE","POTTERY TECHNOLOGY",
                 "POTTER'S WHEEL","VESSELS","CERAMICS","CERAMIC ETHNOARCHAEOLOGY","POTTERY","POTS","POTTERY PRODUCTION","CERAMIC"),
    
    Bone_Tools = c("FISHHOOKS","BONE INDUSTRY","BONE TOOLS","BONE TOOL"),
    
    Play_objects = c("PUBLIC-GOODS GAMES","CHILDS PLAY","SYMBOLIC PLAY","PLAY OBJECTS","DICE","BOARD","GAMES","BOARD GAME"),
    
    # # cultural evol
    Cultural_Evolution = c("COGNITIVE AND CULTURAL EVOLUTION", "TECHNOLOGICAL-CHANGE",	"CULTURAL EVOLUTIONARY","BIOLOGICAL AND CULTURAL EVOLUTION",
                           "CUMULATIVE TECHNOLOGICAL CULTURE","CUMULATIVE CULTURAL-EVOLUTION","CULTURAL MACROEVOLUTION","CULTURAL TAXONOMY",	"PREHISTORIC CULTURAL EVOLUTION",
                           "CULTURAL EVOLUTIONARY THEORY","DARWINIAN ARCHAEOLOGY","DARWINISM","CULTURAL INHERITANCE",	"TECHNOLOGICAL EVOLUTION",
                           "CULTURAL LINEAGES",	"CULTURAL EVOLUTION","CULTURAL-EVOLUTION","HUMAN CULTURAL-EVOLUTION", "FREQUENCY DEPENDENT COPYING",
                           "CULTURAL EVOLUTIONARY MODELS","INNOVATION","SOCIO-CULTURAL EVOLUTION","CULTURAL CHANGE","CULTURE CHANGE","BRANCHING VS. BLENDING",
                           "CULTURAL INNOVATION","RELIGION AND CULTURAL EVOLUTION"),
    
    Niche_Construction = c("CULTURAL NICHE CONSTRUCTION",	"HUMAN NICHE CONSTRUCTION","NICHE","ECOLOGICAL NICHE MODELING", "NICHE CONSTRUCTION","NICHE-CONSTRUCTION","NICHE CONSTRUCTION-THEORY",
                           "NICHE CONSTRUCTION THEORY","ECO-CULTURAL NICHE","AESTHETIC NICHE","NICHE DIVERSIFICATION"),
    
    Complexity = c("COMPLEX ADAPTIVE SYSTEMS","COMPLEX SOCIETIES","CULTURAL COMPLEXITY","COMPLEXITY","EMERGENT COMPLEXITY","SOCIAL COMPLEXITY","TECHNOLOGICAL COMPLEXITY",
                   "SOCIO-POLITICAL COMPLEXITY","SOCIOPOLITICAL COMPLEXITY", "POLITICAL COMPLEXITY","CUMULATIVE CULTURAL","SOCIETAL COMPLEXITY"),
    
    # memetics
    Memetics = c("MEMES","MEME'S EYE-VIEW","MEME","GENES MEMES","MEMETIC INHERITANCE"),
    
    # cultural transmission
    Cultural_Transmission = c("CULTURE TRANSMISSION",	"DIFFUSION", "CULTURAL TRANSMISSION THEORY","MODES OF INHERITANCE","HORIZONTAL TRANSFER","FREQUENCY DEPENDENT COPYING",
                              "PAYOFF-BIASED TRANSMISSION","CULTURAL TRANSMISSION","COPYING","LATERAL/HORIZONTAL TRANSFER","HORIZONTAL TRANSMISSION","STYLISTIC VARIATION",
                              "DIFFUSION OF INNOVATIONS","IDEA-DIFFUSION","CULTURAL DIFFUSION","INFORMATION TRANSMISSION","TECHNOLOGICAL TRANSMISSION",
                              "DIFFUSION OF INNOVATION","SPREAD OF INNOVATION","INNOVATION DIFFUSION","CONFORMIST TRANSMISSION", "TRANSMISSION PROCESSES",
                              "TRAIT TRANSMISSION","TRANS-EURASIA CULTURAL EXCHANGE","TRANSCONTINENTAL CULTURE EXCHANGE","CRISIS OF TRANSMISSION",
                              "SOCIAL TRANSMISSION","INNOVATION PROCESSES","TRANSITIONAL TECHNOLOGY","TRANSMISSION OF COMPLEX TECHNOLOGIES",
                              "TRANSMISSION THEORY","UNBIASED TRANSMISSION","TRAVELING WAVES","TREADMILL MODEL","CULTURAL INFORMATION","BRANCHING VS. BLENDING",
                              "CHILDREN AND CULTURAL TRANSMISSION"),
    
    Social_learning = c("SOCIAL LEARNING","LEARNERS","LEARNED","LEARNING","SOCIAL LEARNING AND","SOCIAL LEARNING STRATEGY","CULTURAL LEARNING","LEARNING-STRATEGIES","KNOWLEDGE","CRAFT LEARNING","CRAFT SPECIALIZATION",
                        "PEDAGOGY","TEACHING","APPRENTICESHIPS","IMITATION","INDIVIDUAL LEARNING","SKILL ACQUISITION","GUIDED VARIATION","COPYING"),
    
    # phylogenetic methods
    Phylogenetic_Cladistic_Methods = c("PHYLOGENETIC TREES","PHYLOGENETIC","INFERENCE","MAXIMUM-PARSIMONY","STATISTICAL INFERENCE",	"COMPARATIVE METHOD","COMPARATIVE METHODS","CLADE SHAPE","PHYLOGENETIC COMPARATIVE","COMPARATIVE METHOD",
                                       "CLADES",	"DIVERGENCE",	"SYSTEMATICS","DIVERGENCE TIMES","DISCRETE TRAITS","PHYLOGENETICS","PHYLOGENY","PHYLOGENETIC ANALYSIS","PHYLOGENETIC TEST","PHYLOGENETIC METHODS",
                                       "PHYLOGENETIC ANALYSES","CULTURAL PHYLOGENETICS","BAYESIAN PHYLOGENETIC INFERENCE","BEAST 2","CLADISTICS","CLADISTIC-ANALYSIS","CLADISTIC ANALYSES","GALTON'S PROBLEM",
                                       "INDEPENDENT CONTRASTS","PHYLOGENETIC COMPARATIVE METHODS","PHYLOGENESIS","ANCESTRAL STATE","ANCESTRAL STATES","CLADE DIVERSITY"),
    
    # modern theories of cultural evolution
    Gene_Culture_CoEvol = c("GENE_CULTURE","GENE-CULTURE COEVOLUTION","DUAL INHERITANCE","GENES MEMES","BIOLOGICAL AND CULTURAL EVOLUTION","DUAL INHERITANCE THEORY",
                            "GENE-CULTURE CO-EVOLUTION","GENE-CULTURE","CO-EVOLUTION","INHERITANCE THEORY","COEVOLUTION","BIOCULTURAL EVOLUTION"),
    
    Evolutionary_Psychology = c("PSYCHOLOGICAL MODEL","PSYCHOLOGICAL","EVOLUTIONARY PSYCHOLOGY","PSYCHOLOGICAL EXPERIMENTATION","CULTURAL EVOLUTIONARY PSYCHOLOGY","PSYCHOLOGY",
                                "SOCIAL BRAIN","SOCIAL BRAIN HYPOTHESIS"),

    Behav_Ecology = c("BEHAVIORAL GAMBIT","HUMAN BEHAVIOURAL ECOLOGY","BEHAVIORAL ECOLOGY"),
    

    # biological/human evolution
    Human_Evolution = c("HUMAN EVOLUTION","MODERN","GENETIC TRANSMISSION","HUMAN ORIGINS","NEANDERTALS","OUT OF AFRICA","ETHNOGENESIS","ARCHAIC HUMANS","HOMO","SAPIENS","PRIMATES",
                        "GENETICS","ORIGINS","MODERN HUMAN-DIVERSITY","HOMO-SAPIENS","MODERN HUMAN TRANSITION","HUMAN-EVOLUTION","MODERN HUMAN ORIGINS","GENE FLOW","PHYSIOLOGY","BIOLOGICAL EVOLUTION",
                        "NEANDERTHALS","NEANDERTHAL","HOMINIDAE","MODERN HUMANS","HOMO SAPIENS","HOMO SAPIENS NEANDERTHALENSIS","HOMO NEANDERTHALENSIS","HOMINID","HUMANS","HOMO ANTECESSOR",
                        "HOMO HEIDELBERGENSIS","ABORIGINES","EARLY HOMO","PLIO-PLEISTOCENE HOMINIDS", "PLIOPLEISTOCENE HOMINIDS","EARLY HOMINID","HOMO-ERECTUS","HUMAN","EARLY-MODERN HUMANS","HOMINIDS","MODERNITY",
                        
                        "BRAIN SIZE"),
    # evolutionary terms/lingo
    Evolutionary_Terms = c("TINBERGEN'S FOUR QUESTIONS", "DERIVED CHARACTERS","ACQUIRED TRAITS","AUTOCATALYTIC NETWORK","ESSENTIALISM","EVOLUTIONARY PERSPECTIVE","POLYGENISTN",
                           "EVOLUTIONARY BIOLOGY",	"EVOLUTIONARY THEORY",	"EVOLUTIONARY GEOARCHAEOLOGY","VARIATIONAL EVOLUTION","MODERN SYNTHESIS",	"EVOLUTIONARY TREND",
                           "RETENTION INDEX","SELECTIVE RETENTION",	"DIVERGENCE",	"DIVERGENCE TIMES","SPINDLE DIAGRAM","EVOLUTIONARY PATTERN","EVOLUTIONARY PROCESS",
                           "EXTENDED EVOLUTIONARY","EXTENDED EVOLUTIONARY SYNTHESIS",	"EVODEVOSOCIO","EVOLUTION OF","EVOLUTION OF COGNITION","HUMANEVOLUTION","EVOLUTION OF HOMO SAPIENS","SYSTEMATICS",
                           "ORIGINATION",	"HOMININ EVOLUTION",	"EVOLUTION","DRIFT","TRANSMISSION","EXTINCTION","TRANSITIONS","SPECIES DIFFERENTIATION","SPECIES EXTINCTION","INHERITANCE",
                           "ADAPTATION","EVOLUTIONARY CONSEQUENCES","POSITIVE SELECTION","ADAPTIVE LAG","REPLICATORS","COPYING ERRORS","PUNCTUATED EQUILIBRIUM","PUNCTUATED EQUILIBRIA",
                           "RECENT POSITIVE SELECTION","HOMOPHILY","TEMPO","MODE","DARWINS FINCHES","LINEAGES","BRANCHING PROCESS","LATERAL GENE-TRANSFER",
                           "EVOLUTIONARY FORCES","INDIRECT SELECTION","NEUTRAL EVOLUTION","MUTATION-DRIFT EQUILIBRIUM","MICROEVOLUTION","EVOLUTIONARY APPROACHES","EVOLUTIONARY APPROACH",
                           "EVOLUTIONARY PROCESSES","NEUTRAL MODEL","NEUTRAL THEORY","RANDOM DRIFT","EVOLUTIONARY","NATURAL SELECTION","MACROEVOLUTION","REACTION-DISPERSAL MODELS","POLYPHENISM",	
                           "ACQUIRED CHARACTERISTICS","LINEAGE","PHENOTYPIC TRAIT","UNIT OF REPLICATION","CONVERGENCE","ISOLATION-BY-DISTANCE","CULTURAL DRIFT","COPYING ERROR"),
    
    Genetics = c("POPULATION GENETICS","GENES MEMES","GENES","MICROCEPHALIN","GENE","SPINDLE DIAGRAM","FOXP2","GENETIC-EVIDENCE","MTDNA","SICKLE-CELL GENE","LACTASE-PERSISTENCE",
                 "PHENOTYPE","PHENOTYPIC ADAPTATION","GENETIC MODIFICATION",
                 "GENE FREQUENCIES","ALLELE","ALLELES","HUMAN MITOCHONDRIAL-DNA","GENETICALLY","GENETIC","LATERAL GENE-TRANSFER","HOMOZYGOSITY TEST","RANDOM GENETIC DRIFT",
                 "ANCIENT DNA","MOLECULAR GENETICS","MITOCHONDRIAL DNA",
                 "GENETIC DIVERSITY","GENETIC-STRUCTURE","GENOME","GENOTYPES"),
    
    # behaviour/cognition
    Behaviour = c("MODERN BEHAVIORS","SYMBOLIC BEHAVIOUR","SYMBOLIC BEHAVIOR","BEHAVIOURAL MODERNITY",	"MODERNITY","MODERN HUMAN-BEHAVIOR","SOCIAL BEHAVIOR","NEANDERTHAL BEHAVIOUR","HUMAN-BEHAVIOR","HUMAN BEHAVIOR",
                         "BEHAVIOR","TECHNOLOGICAL BEHAVIOUR","BEHAVIORAL EVOLUTION","BEHAVIORAL MODERNITY","MODERN BEHAVIOR","BEHAVIORAL RESEARCH","BEHAVIORAL RECIPES",
                         "COOPERATION","COOPERATIVE BEHAVIOR","SOCIAL BRAIN","SOCIAL BRAIN HYPOTHESIS","HUMAN AGENCY","HUMAN COOPERATION","HUMAN SOCIAL BEHAVIOUR","HYGIENE BEHAVIOUR",
                         "BEHAVIOUR","HUMAN BEHAVIORAL","HUMAN BEHAVIOUR","MODERN HUMAN","HOMININ BEHAVIOUR",
                         "ANGER","AGGRESSION","EMOTION",
                         "RITES","PLAY","SYMBOLIC PLAY","OBJECT PLAY","MORTUARY RITUAL"), 
    
    Cognition = c("LANGUAGE DEVELOPMENT","COGNITIVE SCIENCE",	"COGNITIVELY","LANGUAGE-READY BRAIN","SPEECH","CAPACITY FOR LANGUAGE","SENTIENCE","SYMBOLIC COGNITION","PERCEPTION",	
                  "PRIMEVAL MIND","NEURAL REUSE",	"NEUROPRIMATOLOGY",	"NEUROLINGUISTICS",
                  "EVOLUTION OF COGNITION","COMPLEX COGNITION","COGNITION","SOCIAL COGNITION","CULTURE AND COGNITION","COGNIZED LANDSCAPE",
                  "BRAIN","BRAIN SIZE","MEMORY","WORKING-MEMORY","WORKING MEMORY","PREFRONTAL CORTEX","THINKING","GENERAL INTELLIGENCE","INTELLIGENCE","COGNITIVE MECHANISMS",
                  "NEUROIMAGING","BRAIN EVOLUTION","BRAIN RESEARCH","COGNITIVE COUPLING","COGNITIVE DEVELOPMENT", "COGNITIVE AND CULTURAL EVOLUTION","HUMAN BRAIN EVOLUTION",
                  "EXTENDED MIND","CREATIVITY","NEURONS","SOCIAL BRAIN","SOCIAL BRAIN HYPOTHESIS","TRADITIONAL ECOLOGICAL KNOWLEDGE",	
                  "MOTOR SKILL","MOTOR-SKILLS","BASAL GANGLIA",	"NEUROPSYCHOLOGY","NEUROSCIENCE","MENTAL","MENTAL HEALTH","CRANIOFACIAL ANTHROPOMETRY","COGNITIVE ANTHROPOLOGY",
                  "AND THE COGNITIVE AND EVOLUTIONARY SCIENCES","COGNITIVE","COGNITIVE COMPLEXITY","COGNITIVE EVOLUTIONARY SCIENCE","COGNITIVE GADGETS","COGNITIVE PROCESSES",
                  "COGNITIVE SCIENCE OF CULTURE","COGNITIVE-CULTURAL CO-EVOLUTION"),
    
    
    
    Tool_Use = c("PLAY OBJECTS","TECHNICAL BEHAVIOR","TOOL USE","TOOL-USE","TOOL USE BEHAVIOR","STONE-USE PRACTICE","STONE TOOL PRODUCTION",
                 "CRAFT LEARNING","CRAFT SPECIALIZATION"),
    
    Symbolic_Communication = c("ABSTRACT SIGNS","VISUAL SYMBOLS","SYMBOLIC BEHAVIOR","SYMBOLIC BEHAVIOUR","SYMBOLIC COGNITION","SYMBOLIC COMMUNICATION","SYMBOLIC","GESTURE",
                               "SIGNALING THEORY","VISUAL PERCEPTION ERROR"),
    
    
    
    # subsistence
    Subsistence = c("EARLY RICE EXPLOITATION","HOUSEHOLD PRODUCTION","SHELL MIDDEN","FARMERS",	"HUMAN EXPLOITATION","INITIAL DOMESTICATION","BUTCHERY","SHELLFISH EXPLOITATION","MARINE RESOURCES","MARINE SHELL",
                    "FISHING","SUBSISTENCE","HUMAN SUBSISTENCE","HUMAN SUSTAINABILITY","SUBSISTENCE STRATEGIES","TRANSHUMANISM","PALAEO-ECONOMY","MARINE MOLLUSK EXPLOITATION","FOOD QUEST","ECONOMY",
                    "FISHERIES","FISHING (OIL WELLS)","NATURAL RESOURCES","FORAGER SUBSISTENCE DIVERSITY","RICE FARMERS","DIET","WILD-PLANT FOODS","PASTORALISM","DOMESTICATION", "MAIZE AGRICULTURE",
                    "FOOD-PRODUCTION","DIVISION-OF-LABOR","SUBSISTENCE STRATEGY","AGRICULTURE","AGRICULTURAL ORIGINS","SEDENTARY SOCIETIES","LABOR ORGANIZATION","LABOR","AGRICULTURAL POTENTIAL",
                    "AGRICULTURAL TRANSITION","KILL-BUTCHERY","DECLINING FORAGING EFFICIENCY","FORAGING THEORY","BOW","MARITIME ADAPTATIONS",
                    "INTRODUCTION OF BOW AND ARROW","CENTRAL PLACE FORAGING","FORAGING EFFICIENCY","HUNTING STRATEGIES","LAND-USE","CARRYING CAPACITY","RESOURCE INTENSIFICATION"),
    
    HunterGatherer_Forager = c("COMPLEX FORAGERS","PREHISTORIC HUNTER-GATHERERS","HUNTER GATHERERS","MOBILE COMMUNITIES","FORAGING","FORAGING INFORMATION","HUNTERS AND GATHERERS","HUNTING",
                               "INDIGENOUS HUNTER-GATHERERS","HUNTER-GATHERER","HUNTER-GATHERERS","COMPLEX HUNTER-GATHERERS","FORAGER SUBSISTENCE DIVERSITY","FORAGER-COLLECTOR",
                               "HUNTER-GATHERER-FISHERS","GATHERER","HUNTER-GATHERER TECHNOLOGY",	"HUNTING AND GATHERING","HUNTER\\&\\#8211","GATHERERS","HUNTER_GATHERERS","FORAGERS"),
    
    Diet = c("MACRONUTRIENTS","CULINARY PRACTICES","FOOD PLANTS",	"DIETARY TRANSITION","NUTRITIONAL ECOLOGY","NUTRITION","DIET BREADTH","HUMAN METABOLISM",	"FOOD","FOOD PRODUCTION","FOOD SECURITY","FOOD TRADITIONS",
             "PALAEODIETARY",	"FOOD CULTURE",	"FOOD STORAGE",	"FOODWAYS"),
    
    # Art
    Art = c("HOHLENSTEIN-STADEL LOWENMENSCH FIGURINE","PETROGRAPHIC ANALYSIS",	"SHELL BEADS","ART","PALEOLITHIC ART","STENCILS","CAVE ART","ORNAMENTS","MUSIC","SYMBOLISM","FINGER FLUTINGS",
            "PORTABLE ART","PALAEOLITHIC ART","ROCKART","PAINTINGS","PAINTING"),
    
    Design = c("HORSE BLANKET STYLES","FINGERNAIL IMPRESSIONS","MORPHOSPACE",	"DESIGN","STYLISTIC","FUNCTIONAL CONSTRAINTS","DESIGN SPACE","STYLE","TECHNICAL STYLE","STYLISTIC ANALYSES"),
   
    #writing
    Writing = c("ALPHABETIC WRITING","ARCHAIC FORMS OF WRITING","LITERACY","PETROGRAPHIC ANALYSIS","EBA GLYPTICS", "NUCLEAR WRITING","NUMERALS"),
    
    Linguistics = c("PHILOLOGY",	"PROTOLANGUAGE","NEUROLINGUISTICS",	"GLOTTOCHRONOLOGY","INHERITED SPEECH","LINGUISTIC DIVERSITY",
                    "ARCHAIC FORMS OF WRITING",	"ALPHABETIC WRITING",	"SEMANTIC NETWORK",	"SEMIOTICS",	"EVOLUTION OF LANGUAGE",
                    "LINGUISTICS","LANGUAGE EVOLUTION","LANGUAGE","LANGUAGE CHANGE","LANGUAGE ORIGINS","LANGUAGES",
                    "LANGUAGE DEVELOPMENT",	"LANGUAGE-READY BRAIN","SPEECH","CAPACITY FOR LANGUAGE"	),
    
    
    # climate and events
    Climate_and_Catastrophes = c("OXYGEN ISOTOPES",	"CLIMATE","CLIMATE EFFECT","ECOSYSTEM RESPONSE","ENVIRONMENTAL CHANGES","ENVIRONMENTAL","GLACIAL MAXIMUM","LATE HOLOCENE CLIMATE","SEASONALITY","CLIMATE-CHANGE","CLIMATIC VARIABILITY",
                                 "VOLCANIC ERUPTION","CATASTROPHIC EVENT","HEINRICH EVENT","LAACHER SEE","LAACHER SEE-ERUPTION","VOLCANIC FIELD" ,"FLOODS","ENVIRONMENT","COLD ADAPTATION",
                                 "HEINRICH EVENT 4","VOLCANIC ERUPTIONS","MIS 2",	"MIS 11","MIS 3","EVENTS","LAACHER-SEE-ERUPTION","VOLCANO","CLIMATIC STRESS","CAMPANIAN IGNIMBRITE ERUPTION", "VOLCANIC-ERUPTIONS",
                                 "TIPPING POINTS","VULNERABILITY","RESILIENCE","PALEOCLIMATOLOGY",	"PALEOHYDROLOGY","ENVIRONMENTAL ARCHAEOLOGY","ENVIRONMENTAL CHANGE","SEA LEVEL CHANGE",
                                 "4.2 KA",	"EL-NINO",	"CHIEMGAU METEORITE IMPACT", "COSMIC IMPACT",	"ERUPTION",	"TSUNAMI",	"FLOOD", "PALEOFLOOD HYDROLOGY","DRY","ICE-FREE CORRIDOR",
                                 "VOLCANOES",	 "EARTHQUAKES",	"HOLOCENE CLIMATE",	"PALEOCLIMATE",	"PALEOENVIRONMENTAL CHANGES", "SEA LEVEL","SEA-LEVEL",	"SEA-LEVEL HISTORY","HYDROCLIMATIC CONTEXTS",
                                 "PAST CLIMATE-CHANGE", "TEMPERATURE", "TEMPERATURE HISTORY", "THERMAL ALTERATION",	 "LAKE DELTA O-18","ENVIRONMENTAL COLLAPSE","TEPHRA STUDIES",
                                 "ABRUPT CLIMATE CHANGE",	"SUMMER MONSOON",	"MONSOON",	"ASIAN SUMMER",	"CLIMATE CHANGE",	"CASCADE MODEL","PALAEO-EARTHQUAKE","PALAEOCLIMATE","ATMOSPHERIC DUST",
                                 "PALEOCLIMATE RECORDS","PALEOFLOOD","SOCIAL VOLCANOLOGY","PALEOCLIMATIC","HUMID","ARID","ARIDITY","DRIER","COLLAPSE","AFRICAN HUMID PERIOD","ENVIRONMENTAL CONDITIONS",
                                 "CLIMATE INSTABILITY",	"CLIMATE VARIABILITY","HOLOCENE CLIMATE VARIABILITY","DISASTER","DROUGHT","DRY EVENT","MEGADROUGHT","CLIMATE AND ENVIRONMENTAL CHANGE","CLIMATE EVENT",
                                 "GLACIATIONS",	"ICE CAP","ICE CORE",	"NEOGLACIATION",	"TREE-RING RECORD","VOSTOK ICE CORE","2.8 KA BP","4.2 KA EVENT","4.2 OR 4.0 KYR CLIMATIC EVENT",
                                 "5400 A BP EXTREME WEAKENING EVENT","CLIMATE AND HUMANS",	"CLIMATE IMPACT",	"PAST CLIMATE CHANGE",	"CLIMATIC"	),
    # periods
    Geochronological_terms = c("QUATERNARY","EARLY HOLOCENE","LATE HOLOCENE","MID-HOLOCENE",	"MIDDLE AND LATE PLEISTOCENE",	"PLEISTOCENE AUSTRALIA","LATE PLIOCENE","LATEST MIDDLE PLEISTOCENE","MIDHOLOCENE",
                               "PLEISTOCENE-HOLOCENE BOUNDARY","PLEISTOCENE-HOLOCENE TRANSITION","PLEISTOCENE","UPPER PLEISTOCENE","MIDDLE PLEISTOCENE","EARLY PLEISTOCENE","TEPHROCHRONOLOGY","PLEISTOCENE CHRONOLOGY",
                               "PLIO-PLEISTOCENE","LATE PLEISTOCENE ARCHAEOLOGY","MIDDLE HOLOCENE","PLEISTOCENE ARCHAEOLOGY","MID_HOLOCENE","PLEISTOCENE SITE"),
    
    Palaeolithic = c("ACHEULEAN ORIGINS","QUATERNARY","PALEOLITHIC TAXONOMY",	"PALEOLITHIC AGE TO NEOLITHIC AGE","PALEOINDIAN POINTS","LATE STONE AGE",	"EARLY STONE AGE",	"INITIAL UPPER PALEOLITHIC","ACHEULIAN","LATER ACHEULEAN","ACHEULEAN SITE","UPPER PALAEOLITHIC","UPPER PALEOLITHIC","LOWER PALEOLITHIC","MIDDLE TO UPPER PALEOLITHIC TRANSITION",
                     "MIDDLE PALEOLITHIC","KEILMESSERGRUPPEN","PALEOLITHIC ARCHAEOLOGY","PALEOLITHIC","AURIGNACIAN","MIDDLE-UPPER PALEOLITHIC TRANSITION","ACHEULEAN","SIBERIAN PALEOLITHIC",
                     "PALAEOLITHIC","MOUSTERIAN","BARADOSTIAN","FEDERMESSER","STONE-AGE","OLDOWAN","LATE PALEOLITHIC","UPPER PALEOLITHIC TRANSITION","PALEOFLOOD HYDROLOGY",
                     "LAST INTERGLACIAL","LATE GLACIAL","HOLOCENE","MIDDLE-HOLOCENE","HOHLENSTEIN-STADEL LOWENMENSCH FIGURINE","PALAEOLITHIC ARCHAEOLOGY",	"MIDDLE-TO-UPPER PALEOLITHIC",
                     "STONE AGE","LAST GLACIAL MAXIMUM","MIDDLE PALAEOLITHIC","LOWER/MIDDLE PALEOLITHIC","GRAVETTIAN","EARLY AURIGNACIAN","LOWER PALAEOLITHIC","MIDDLE STONE",
                     "MAGDALENIAN","UPPER MAGDALENIAN","MIDDLE/UPPER PALEOLITHIC TRANSITION","PALCOENVIRONMENTS","PALEOAMERICANS",	"PALAEODEMOGRAPHY",	"PALEOLITHIC TRANSITION",
                     "PALEOCLIMATOLOGY",	"PALEOHYDROLOGY","MIDDLE/UPPER","AZILIAN","BROMME CULTURE","ROSTAMIAN","PALEOLITHIC TRANSITIONS","EARLIER STONE AGE","ATERIAN",
                     "PALEOLITHIC TRANSITIONAL","EPIPALAEOLITHIC","CARPATHIAN UPPER PALAEOLITHIC","HOMINID SITE","PALEOLITHIC SITE","EARLY UPPER PALAEOLITHIC",
                     "FINAL PALAEOLITHIC","EARLY UPPER PALEOLITHIC","LATE PLEISTOCENE","ULUZZIAN","EARLIER STONE AGE","LATE ACHEULIAN","MOVIUS","MOVIUS LINE","THE MOVIUS LINE (ML)",
                     "STONE-AGE SITES"),
    
    Palaeoindian = c("LATE WOODLAND","WOODLAND CERAMICS","CALIFORNIA INDIANS","PALEOINDIAN","PALEOINDIANS","CHUMASH" ,"INUIT PEOPLES","PALEO CROSSING 33ME274","PRE-CLOVIS"),
    
    African_Stone_Age = c("HOWIESONS POORT","POST-HOWIESONS POORT","POST-HOWIESON'S POORT",	"HOWIESONS-POORT LAYERS",	"MIDDLE STONE-AGE","LATER STONE-AGE","MSA SITE","MIDDLE STONE AGE ARCHAEOLOGY",
                          "AFRICAN MIDDLE STONE AGE","MIDDLE STONE AGE","PRE-OLDOWAN","DEVELOPED OLDOWAN","EARLIEST OLDOWAN","LATER STONE AGE",
                          "MIDDLE AND LATER STONE AGE","MIDDLE-STONE-AGE","EARLY MIDDLE STONE AGE"),  
    
    # "MESOLITHIC"
    Mesolithic = c("EPIPALAEOLITHIC/MESOLITHIC","PALEOLITHIC AGE TO NEOLITHIC AGE","MESOLITHIC POTTERY",
                   "EARLY MESOLITHIC",	"LATE MESOLITHIC","MESOLITHIC", "KHARTOUM MESOLITHIC","SHELL MIDDEN"),
    
    # Neolithic
    Neolithic = c("PALEOLITHIC AGE TO NEOLITHIC AGE","AGRICULTURE","DOMESTICATION","NEOLITHIC EUROPE","EARLY AGRICULTURE","NEOLITHIC TRANSITION","LINEARBANDKERAMIK CULTURE","FORAGER-FARMER","NEOLITHIC",
                  "NEOLITHIC ARCHAEOLOGY","EARLY NEOLITHIC",	"NEOLITHIC SOCIETIES",	"NEOLITHIC SPREAD",	"AGRICULTURAL POTENTIAL","AGRICULTURAL TRANSITION",
                  "FARMERS",	"INITIAL DOMESTICATION","NATUFIAN","NEOLITHIC AND BRONZE AGE","LATE NEOLITHIC","LATE NEOLITHIC AND BRONZE AGE","LATE NEOLITHIC AND BRONZE PERIODS",
                  "IRISH MEGALITHS","MEGALITHS","NEOLITHIC REVOLUTION","NEOLITHISATION","BELL BEAKER CULTURE","AGRICULTURAL DEVELOPMENT","ORIGINS OF AGRICULTURE",
                  "IRISH AGRICULTURAL CONDITIONS","NEOLITHIC PERIOD"),
    
    Bronze_Age = c("LATE NEOLITHIC AND BRONZE AGE","LATE NEOLITHIC AND BRONZE PERIODS","BRONZE-AGE","LATE BRONZE AGE","NEOLITHIC AND BRONZE AGE",	"EBA GLYPTICS",
                   "EBA SOUTHERN LEVANT",	"EBA URBANISM",	"LATE BRONZE-AGE","EARLY BRONZE AGE","EARLY BRONZE METALLURGY","CHINESE BRONZE AGE","BRONZE",
                   "EUROPEAN BRONZE AGE","COPPER","IRON AGES","EARLY BRONZE-AGE","CHALCOLITHIC PERIOD","MIDDLE BRONZE AGE","BRONZE AGE"),
    
    Iron_age = c("LA TENE PERIOD","IRON AGES","IRON AGE","LATE IRON AGE SCANDINAVIA","VIKINGS","IRON-AGE"),
    
    Metallurgy = c("COPPER","METAL","MONSOON STEEL","BRONZE INDUSTRY","METALLURGY", "IRON SMELTING FURNACES","ASIAN METALLURGY","TATARA","FURNACES",
                   "IRON","IRON SMELTING","BRONZE","EARLY BRONZE METALLURGY","CAST IRON","COPPER CULTURE","COPPER SMELTING","SLAG"),
    
    Ancient = c("ROMAN","ROMAN EMPIRE", "ANCIENT","ANCIENT CERAMICS","LATE ANTIQUITY","ANTIQUITY","ANCIENT-CITY"),
    

    
    
    # spatio temporal
    Spatial = c("SPATIAL SIMULATION",	"SPATIO TEMPORAL","GEOGRAPHICAL DISTRIBUTION","SPATIAL DISTRIBUTION","SPATIOTEMPORAL ANALYSIS","SPATIAL", "RELIEF TOPOGRAPHY",  "SPATIOTEMPORAL",
                "LANDSCAPE", "COGNIZED LANDSCAPE","SPATIAL AUTOCORRELATION", "LOCAL SPATIAL AUTOCORRELATION","GEOGRAPHICAL VARIATION (SPECIES)","GEOGRAPHICAL VARIATION","SPATIALLY",
                "TERRITORIALITY","PALEOGEOGRAPHY","ISOLATION-BY-DISTANCE","ISOLATED","GIS",	"SPATIAL ANALYSIS",	"ANTHROPOGENIC LANDSCAPES",	"GEOSPATIAL",	"ENVIRONMENTAL-CHANGE","TERRITORY",
                "SPATIAL DIFFUSION","SPATIAL EXPANSION","SPATIAL PATTERNS","SPATIAL-TEMPORAL","SPATIOTEMPORAL DISTRIBUTION PATTERNS","ECOLOGICAL ADAPTATION","ECOLOGICAL IMPERIALISM","ECOLOGICAL NICHE MODELING",
                "PROVENANCE RECONSTRUCTION","MACRO-REGIONAL INTERACTION","SPATIAL SCALE","GIS ANALYSIS","GEOGRAPHICALLY","REACTION-DISPERSAL MODELS"),
    
    Temporal = c("SPATIO TEMPORAL","SPATIOTEMPORAL ANALYSIS","SPATIAL-TEMPORAL","SPATIOTEMPORAL DISTRIBUTION PATTERNS","TEMPORAL DISTRIBUTION","TEMPORAL FREQUENCY DISTRIBUTIONS",
                 "SEQUENTIAL DATA","AORISTIC METHODS","STASIS","PACE","SPEED","RAPIDLY","CYCLE","SPATIOTEMPORAL","SHIFT","LONG_TERM","LARGE_SCALE","DYNAMICS","DYNAMIC","CYCLES",
                 "TEMPORAL RESOLUTION","TEMPORAL TENDENCIES","TEMPORAL FREQUENCY-DISTRIBUTIONS","TIME-SERIES",	"DEEP TIME","PHASE","LONG-TERM","POST-HARVEST",
                 "TIME AVERAGING","TIME-AVERAGING"),
    
    Macro_scale = c("COSMIC EVOLUTION",	"CULTURAL MACRO-EVOLUTION","LONG-TERM DATA SETS","GLOBAL PATTERNS","MACRO-EVOLUTION","GLOBAL-CHANGE","GLOBAL","GLOBAL ETHIC","MACROHISTORY"),
    
    Comparative = c("COMPARATIVE APPROACH","COMPARATIVE ARCHAEOLOGY","COMPARATIVE METHOD","COMPARATIVE RELIGION","COMPARATIVE STUDY","COMPARATIVE STUDY","STYLISTIC COMPARISON","MODEL COMPARISON"),
    
    Cross_Cultural = c("CROSS-CULTURAL ETHNOGRAPHY","CROSS-CULTURAL METHODOLOGY","CROSS-CULTURAL STUDIES","CROSS-CULTURAL VARIATION"),
    
    # ecology/ecosystems
    Ecology_Environment = c("POLLEN-DERIVED BIOMES","ECOLOGY","RAINFALL VARIABILITY","FRESHWATER ECOSYSTEM","DRAINAGE","PALEOECOLOGY","PALEOENVIRONMENT","ECOLOGICAL","PALEOECOLOGICAL","BIOSPHERE",
                "BALDWIN EFFECT","CULTURAL ECOLOGY","NUTRITIONAL ECOLOGY","R-/K-SELECTION",	"PALCOENVIRONMENTS","HUMAN-DOMINATED ECOSYSTEMS","LAND COVER","HABITATS","HUMAN BIOGEOGRAPHY",
                "EVOLUTIONARY ECOLOGY","DIVERSIFICATION","HISTORICAL ECOLOGY","VULNERABILITY","RESILIENCE","CASCADE MODEL","QUATERNARY PALEOECOLOGY","NATURAL ENVIRONMENT",
                "POPULATION ECOLOGY","BIODIVERSITY","CARRYING-CAPACITY","ENVIRONMENTAL DETERMINISM","AFFORDANCE","NATURAL RESOURCES","REGIONAL SYSTEMS","FORESTS","PALAEOENVIRONMENT",
                "MAXENT","ECODYNAMICS",	"ECOLOGICAL ANTHROPOLOGY","TINBERGEN'S FOUR QUESTIONS","TRADITIONAL ECOLOGICAL KNOWLEDGE","HUMAN ECOLOGICAL PATTERNS","HUMAN ECOLOGY",
                "HUMAN EVOLUTIONARY ECOLOGY","HUMAN POPULATION ECOLOGY",	"FOREST","GRASSLANDS","HIGH-ALTITUDE","ECOLOGICAL ANTHROPOLOGY","LANDSCAPE CHANGE",
                "ECOSYSTEMS","ENVIRONMENTAL RECONSTRUCTION","FLUCTUATING ENVIRONMENT","HUMAN BEHAVIORAL ECOLOGY","HUMAN-ENVIRONMENT NEXUS",
                "HUMAN ECODYNAMICS","ENVIRONMENTS","PALEOENVIRONMENTAL","STONE AGE ENVIRONMENTS","HUMAN-ENVIRONMENTAL INTERACTION"), 
    
    Geoscience = c("AQUIFERS","LOESS PLATEAU","LOESS-PALEOSOL SEQUENCE","NATURAL HISTORY","DEPOSITION RATES","EVOLUTIONARY GEOARCHAEOLOGY","THIN-SECTION PETROGRAPHY","CRYSTALLOGRAPHY OF",	"QUARTZ",	"HYDROGEOMORPHIC CONTEXT",
                   "GEOLOGICAL","SHEET EROSION","TECTONICS","STALAGMITE","QUATERNARY UPLIFT",	"RESOLUTION GEOCHEMICAL RECORD",	"ROCK",	"SEDIMENTARY RECORDS",	"TEPHRA STUDIES","TEPHROCHRONOLOGY","QUARTZITE","ALLUVIUM (QAL)",
                   "SEDIMENTS",	"SILICA MINERALS","MICROMORPHOLOGY","SITE FORMATION",	"SITE-FORMATION",	"SOIL",	"GEOARCHAEOLOGY",	"GEOMORPHOLOGY","SEDIMENT GEOMETRY","GLADE DIVERSITY ANALYSIS"),
    # palaeoantrop
    Palaeoanthropology = c("BASAL GANGLIA",	"CRANIOFACIAL ANTHROPOMETRY","PALEOANTHROPOLOGY","PALAEOANTHROPOLOGY","PLEISTOCENE HUMAN","ARTIFICIAL CRANIAL DEFORMATION","SEXUAL-DIMORPHISM",
                           "OLDOWAY BONE BEDS","SEX-DIFFERENCES","ANTHRACOLOGY",	"PROTEIN TOXICITY","MENOPAUSE",	"SKELETAL",
                           "ENAMEL","DENTAL ENAMEL","CRANIUM","BODY MASS","SKELETON","ANATOMY","BONE","BONE AND BONES","UNGULATE","UNGULATA","SKELETAL REMAINS","BRAIN SIZE",
                           "BONE-COLLAGEN","BIOLOGICAL ANTHROPOLOGY","CRANIAL MORPHOLOGY","CRANIOMETRICS",
                           "HYPOXIA"), 
    Primatology = c("GREAT APE","SAVANNA CHIMPANZEES","CHIMPANZEE","CHIMPANZEES PAN-TROGLODYTES","NEUROPRIMATOLOGY","PRIMATE ARCHAEOLOGY",	"PRIMATE",	"RHESUS-MONKEYS",	"CAPUCHIN MONKEYS","APES IMPLICATIONS",	
                    "WILD CHIMPANZEES","MONKEYS","CHIMPANZEE POPULATIONS","APES","PAN-TROGLODYTES","CHIMPANZEES","PAN-PANISCUS","PAN TROGLODYTES","PRIMATES"),
    
    # zooarch
    Fauna = c("ZOOARCHAEOLOGY","RANGIFER","LARGE GAME","ZOOARCHEOLOGY","UNGULATES","METAPODIAL","ANIMAL","FISH","REINDEER","MAMMALS","RIVER CARIBOU HERD","MAMMALIA",
              "ANIMAL CULTURE","ANIMAL CUTLURES9","ANIMAL DYNAMICS","ANIMISM","HUMAN-ANIMAL",
              "FAUNA","VERTEBRATE","SMALL MAMMALS","LARGE GAMES","PAPIO","BISON","CAPRA IBEX","ANIMALS","HORSE","EQUIDAE","ANIMALIA","SALMON",	"BUFO-MARINUS","GIANT TOAD",
              "CARNIVORE TOOTH MARKS","SHEEP","CATTLE", "MIDDENS",	"LARGE SHELL","R-/K-SELECTION","LARGE-MAMMAL FAUNA","ANIMAL TRADITIONS","MAMMOTH","VERTEBRATES",
              "ANIMAL CULTURES",	"ANIMAL SOCIAL NETWORKS","BIRDS SONG","BONE-COLLAGEN","GOATS CAPRA-HIRCUS"),   
    # bioarch
    Flora = c("VEGETATION",	"BIOLOGY",	"BIOMES",	"FOOD PLANTS",	"POLLEN RECORD","WILD CEREALS","GALIUM APARINE","PERILLA FRUTESCENS","BIOLOGICAL","PLANT","PHYTOLITH","PHYTOLITHS",
                "POLLEN",	"POLLEN DATA","POLLEN-DERIVED BIOMES",	"MANIOC",	"VEGETATION HISTORY","FORESTS","ARCHAEOBOTANY","POLLEN ANALYSIS","PLANTS",
                "BIOARCHAEOLOGY","CHILENSIS MOL. STUNTZ","MAIZE"),
    
    Ethnoarchaeology = c("ETHNOLOGY",	"ETHNOARCHAEOLOGY","CERAMIC ETHNOARCHAEOLOGY"),
    
    Historical = c("HISTORICAL ARCHAEOLOGY","PROTOHISTORIC","QUANTITATIVE HISTORY","INDIGENOUS HISTORY","HISTORICAL RECORD","HISTORICAL SOCIOLOGY","HISTORY AND ARCHAEOLOGY"),
    
    
    # morphometrics/morphology
    Morphometrics = c("3D GEOMETRIC","GEOMETRIC MORPHOMETRIC ANALYSES","MORPHOMETRIC","MORPHOLOGY","LENGTH ESTIMATION","MORPHOMETRY","GEOMETRIC MORPHOMETRICS","MORPHOMETRICS",
                      "MORPHOLOGICAL","GEOMETRIC","GEOMETRICS","MORPHOMETRIC-ANALYSIS","MORPHOSPACE",
                      "CRANIAL MORPHOLOGY","CRANIOMETRICS","GEOMETRIC MORPHOMETRIC-ANALYSIS","DIGITAL MORPHOMETRICS","MORPHOMETRIC VARIABILITY","ALLOMETRY","FOURIER-ANALYSIS"), 
    
    Quantitative_Methods = c("QUANTITATIVELY","STATISTICS","SIMULTANEOUS CONFIDENCE-INTERVALS","STOCHASTIC-MODELS",	"PROCESSUAL ARCHAEOLOGY","R PACKAGE","DATA ANALYSIS","QUANTITATIVE HISTORY","STOCHASTIC PROCESSES","PARAMETER-ESTIMATION","MATHEMATICAL MODELLING",	"INFERENCE",	"PROBABILITY-DISTRIBUTIONS","COMPUTATIONAL CHALLENGES",	"BAYESIAN-INFERENCE", 
                             "SUMMED PROBABILITIES","REGRESSION","QUANTITATIVE ANALYSIS","BOOTSTRAPPING","SUMMED PROBABILITY DISTRIBUTIONS","QUANTITATIVE-ANALYSIS", "EMPIRICAL","EMPIRICAL DATA",
                             "QUANTITATIVE METHODS","AUTOCORRELATION","AUTO-CORRELATION","POISSON PROCESS","MEAN-SQUARED DISPLACEMENT","FREQUENCY-BIASED","MULTIVARIATE","DATABASE","NUMERICAL METHOD","STATISTICAL","HYPOTHESIS TESTING",
                             "APPROXIMATE BAYESIAN COMPUTATION", "EWENS SAMPLING DISTRIBUTION","DISTANCE GRAPHS","MAXENT","EMPIRICAL EVIDENCE","BAYESIAN","BAYESIAN MODELS","ARTIFICIAL INTELLIGENCE",
                             "MAXIMUM-PARSIMONY","STATISTICAL INFERENCE","SAMPLING SCHEME","LIKELIHOOD","DIAGRAMS","OUTLIER DETECTION","CORRESPONDENCE ANALYSIS","COMPUTER","STATISTICALLY","EXTERNAL VALIDITY","INTERNAL VALIDITY","MATHEMATICAL ANALYSIS",
                             "NEUTRALITY TESTS","TIME AVERAGING","TIME-AVERAGING","REACTION-DISPERSAL MODELS","TEMPORAL FREQUENCY-DISTRIBUTIONS","MONTE CARLO","QUANTITATIVE","SUMMED PROBABILITY DISTRIBUTION",
                             "COMPUTATIONAL",	"COMPUTATIONAL ARCHAEOLOGY","COMPUTATIONAL MODELING",	"LONG-TERM DATA SETS","DATABASES","COMPUTATIONAL MODELLING"),
    
    # 
    Scientific_methods = c("STABLE-ISOTOPE ANALYSIS","STABLE-ISOTOPES","NITROGEN","LAKE DELTA O-18","INTELLIGENCE TESTING","EXPERIMENTAL","MICROWEAR ANALYSIS","ANALYTICAL METHOD",
                           "TREE-RING RECORD","VOSTOK ICE CORE","INVESTIGATING MICROWEAR POLISHES","ISOTOPE RATIOS","BLIND TESTS","AUTOMATIC PHOTOGRAMMETRY",	"(C-14) DATE DENSITIES",
                           "STABLE CARBON AND NITROGEN ISOTOPES","STARCH ANALYSIS","ARCHAEOMETRY","STRONTIUM ISOTOPES","ISOTOPE STAGE","MARINE ISOTOPE","TEST HYPOTHESES","TESTABLE HYPOTHESES",
                           "TERRESTRIAL LASER SCANNING","NATURAL SCIENCES","SURFACE PROPERTY","TAPHONOMY","SITE-FORMATION PROCESSES","SEQUENCE STRATIGRAPHY","GEOCHRONOLOGY",
                           "LOESS","GEOLOGY","SEDIMENTOLOGY","GEOLOGICAL RECORD","KARST","STRATIGRAPHY","STRATIGRAPHIC CORRELATION",  "VARNISH MICROSTRATIGRAPHY",
                           "ANALYTICAL PROTOCOLS","LITHOSTRATIGRAPHY","DETECTION METHOD","MICROSCOPY","CHEMISTRY","CONCENTRATION (PARAMETERS)","USE-WEAR","CONTROLLED STUDY",
                           "FOSSIL","FOSSILS","PALEONTOLOGY","CONFOCAL MICROSCOPY","COUNTING DEVICES","COSMONUCLIDE","CALIBRATION"), 
    
    # modelling
    Modelling_Simulating = c("BAYESIAN MODELS","SPECIES MODEL","SIMULATIONS","STIMULATED","MODELED","ABM","AGENT_BASED MODEL","AGENT-BASED","DISTRIBUTION MODELLING","SPATIAL SIMULATION",
                             "MODEL COMPARISON","COMPUTATIONAL MODELING",	"COMPUTATIONAL MODELLING", "COMPUTER SIMULATION","COMPUTER-SIMULATION", "MODELS","MODEL","MODELING", "MODELLING",
                             "BIOLOGICAL MODEL","MATHEMATICAL MODEL","STATISTICAL MODEL","NUMERICAL MODEL","AGENT-BASED MODELLING","AGENT-BASED SIMULATION","AGENT-BASED MODELING","CULTURAL MODELING",
                             "CULTURAL DISSEMINATION MODEL","COMPUTATIONAL MODEL","COMPUTER MODELING","SPATIALLY EXPLICIT SIMULATION","MAXENT","AGENT-BASED MODEL","STIMULATED VARIATION",
                             "INDIVIDUAL-BASED SIMULATION","OPTIMALITY MODELING","SIMULATION","REACTION-DISPERSAL MODELS","EXPERIMENTAL SIMULATION","SIR MODEL","CULTURAL EVOLUTIONARY MODELS",
                             "EVOLUTIONARY MODELS","AGENT_BASED","MODEL SYSTEM"), 
    
    Networks = c("DEFAULT-MODE NETWORK","SEMANTIC NETWORK","MARITIME NETWORKS","SOCIAL NETWORK","COMMUNITY INTERACTION","POPULATION CONNECTIVITY","NETWORK","SOCIAL NETWORK MAINTENANCE","SOCIAL NETWORKS",
                 "NETWORKS","SOCIAL NETWORK ANALYSIS","ARCHAEOLOGICAL NETWORKS","NETWORK ARCHAEOLOGY","NETWORK PROPERTIES","AUTOCATALYTIC NETWORK",
                 "MACRO-REGIONAL INTERACTION","CENTRALITY","ASYMMETRICAL EXCHANGE","CULTURAL INTERACTION","ELITE EXCHANGE"),
    
    # methods
    Methods = c("METHODOLOGY","STYLISTIC ANALYSES","ATTRIBUTE ANALYSIS","MORPHOLOGICAL ANALYSIS",
                "ARCHAEOLOGICAL METHOD AND THEORY","METHODOLOGICAL CONSIDERATIONS",
                "WORLD-WIDE-WEB","INTERNET"),
    
    Absolute_Dating = c("RADIOCARBON CALIBRATION","C-14",	"RADIOCARBON-DATES","(C-14) DATE DENSITIES","LUMINESCENCE DATING","DATES","CHRONOLOGY", "OSL DATING",	 "MIS 2",	"MIS 11","MIS 3",  "C14",
                        "RADIOCARBON","RADIOCARBON DATING","THERMOLUMINESCENCE","DATING METHOD","MARINE ISOTOPE STAGE","RADIOCARBON DATES","TEPHROCHRONOLOGY",
                        "ELECTRON SPIN RESONANCE DATING","ELECTRON SPIN RESONANCE","ELECTRON SPIN RESONANCE SPECTROSCOPY","RADIOMETRIC DATING","MARINE ISOTOPE STAGES","OXYGEN ISOTOPE STAGE 3",
                        "BAYESIAN RADIOCARBON DATE","ABSOLUTE DATING","ESR DATING","AGE CALIBRATION","CARBON 14","C-14 DATING","RADIOCARBON CHRONOLOGY","U-PB","RADIOCARBON TIMESCALE",  
                        "CHRONOMETRIC DATA","OPTICALLY STIMULATED LUMINESCENCE","AGE DETERMINATION","OSL","CALIBRATION"),
    
    Typology_Taxonomy = c("TAXONOMY","MICRO-SERIATION","ARTIFACT TYPES",	"CULTURAL TAXONOMY","TECHNO-TYPOLOGY","TYPE DIVERSITY","TYPOLOGY AND CLASSIFICATION","TECHNO_COMPLEX",
                          "LITHIC TYPOLOGY","LITHIC TYPOLOGIES","TAXA","TYPOLOGICAL","SERIATION ANALYSIS","ARCHAEOLOGICAL SYSTEMATICS",
                          "PALEOLITHIC TAXONOMY",	"TYPOLOGY","CLASSIFICATION","PARADIGMATIC CLASSIFICATION" ,"SERIATION"),
    
    
    # theories
    Theoretical_approaches = c("THEORETICAL","RANGE THEORY","THEORETICAL MODEL","RADICAL ENACTIVISM","COGNITIVE ARCHAEOLOGY","META-REPRESENTATION","THEORY OF MIND","ARCHAEOLOGICAL THEORY",
                               "ENVIRONMENTAL RISK HYPOTHESIS","THEORY","HYPOTHESIS","THEORY NEED","CULTURAL DISSEMINATION MODEL","NEO-MARXISM","FISHERS FUNDAMENTAL THEOREM",
                               "ARCHAEOLOGICAL METHOD AND THEORY", "SIGNALING THEORY","IDENTITY THEORY",	"DEMOGRAPHIC TRANSITION",
                               "MIDDLE-RANGE THEORY",	"ARCHAEOLOGICAL FREQUENCY SERIATION",	"ARCHAEOLOGICAL METHODS",	"ARCHAEOLOGICAL METHODS AND THEORY",	
                               "CONFORMISM",	"NEW EMPIRICISM",	"NORMATIVE THEORY",	"PROCESSUAL ARCHAEOLOGY","RESILIENCE THEORY","ESSENTIALISM","DECISION THEORY",	
                               "WORLD-SYSTEMS ANALYSIS",	"WORLD-SYSTEMS THEORY","WORLD-SYSTEMS", "MODEL SYSTEM",
                               "PHILOSOPHICAL NATURALISM",
                               
                               "FRANZ BOAS","BOAS","CULTURAL ANTHROPOLOGY","NEO-DARWINISM",
                               
                               "FRIEDRICH WILHELM NIETZSCHE",
                               "GUSTAV SCHWALBE",
                               "HABITUS",
                               "DARWINIAN","CHARLES DARWIN",
                               "DARWINIAN THEORY","DARWINIAN EVOLUTIONARY","DARWINIZATION OF CULTURE",
                               "SOCIAL DARWINISM","UNIVERSAL DARWINISM",
                               "EVOLUTIONIST","EVOLUTIONISM",
                               "AXELROD'S",
                               "ANTONIO GRAMSCI",
                               "JARED DIAMOND",
                               "AUTOPOIESIS", # luhmann
                               "CULTURAL ATTRACTOR THEORY",
                               
                               "PHILOSOPHY","PHILOSOPHICAL",
                               "AESTHETICS","AESTHETIC MIND","ANTHROPOLOGY OF AESTHETICS",
                               
                               "AGENCY",
                               
                               "SYSTEMS SCIENCE",
                               "SYSTEMS THEORY"),
    
    # wissenschaftstheorie
    Theory_of_science = c("PARADIGM SHIFT","RESEARCH DESIGN","HISTORY OF PREHISTORY","EPISTEMOLOGY","EXCAVATION TECHNIQUES","CHRONOLOGY AS TOPIC","HISTORY OF ARCHAEOLOGY",
                             "SCIENTIFIC RACISM","CRITIQUE", "COLONIAL",	"COLONIALISM",	"ACADEMIC COPYING",	"PHILOSOPHY OF SOCIAL SCIENCES","CENTENNIAL PAPER"),
    
    Critical_Controversial = c("CRITICALLY","CRITICISMS","DISCUSSES","CONTROVERSIAL","CONTROVERSY","PROBLEMATIC"),
    
    Inter_Multidisciplinary = c("MULTIDISCIPLINARY","INTERDISCIPLINARY RESEARCH","INTERDISCIPLINARITY","INTERDISCIPLINARY","INTERDISCIPLINARY NETWORKS"),
    
    
    # demography
    Demography = c("PREHISTORIC DEMOGRAPHY","DEMOGRAPHY","POPULATION-GROWTH","POPULATION REGULATION","POPULATION FLUCTUATIONS","DEPOPULATION","POPULATION-STRUCTURE","LOW BIRTHRATE",
                   "POPULATIONS","DEMOGRAPHIC HISTORY","POPULATION DENSITY","POPULATION SIZE","FISHERS FUNDAMENTAL THEOREM","HUMAN-POPULATION","HUMAN POPULATIONS","POPULATION GROWTH",
                   "ASIAN POPULATIONS" ,"POPULATION AGGREGATION","PREHISTORIC POPULATION","POPULATION BOTTLENECKS","TENFOLD POPULATION INCREASE","HUMAN-POPULATIONS",
                   "PALEODEMOGRAPHY","POPULATION ECOLOGY","HUMAN POPULATION ECOLOGY","ARCHAEOLOGICAL DEMOGRAPHY",	"PALAEODEMOGRAPHY","PALEOESKIMO DEMOGRAPHY","DEMIC",
                   "POPULATION","POPULATION-SIZE","NATURAL-POPULATIONS","POPULATION_LEVEL","SETTLEMENT POPULATION","POPULATION HISTORY","DEMOGRAPHIC","DEMOGRAPHY AND CULTURAL",
                   	"EVOLUTIONARY DEMOGRAPHY","FINITE POPULATION SIZE","ADULTS","POPULATION DECLINE","SOCIAL BRAIN","SOCIAL BRAIN HYPOTHESIS",
                   "HUMAN POPULATION SIZE","GROUP-SIZE","HUMAN POPULATION","POPULATION DENSITIES"	),   # population can also be non-human
    
    Children = c("CHILDREN","CHILDHOOD","CHILD","CHILDREN AND CULTURAL TRANSMISSION","PARENTAL INVESTMENT STRATEGY","CHILDS PLAY"),
    
    Mobility = c("LOGISTIC MOBILITY","PEOPLING","HUMAN COLONIZATION","DEMIC DIFFUSION","HOMININ DISPERSAL","COLONISATION", "MOVEMENT","HUMAN DISPERSAL","COLONIZATION","MIGRATIONS",
                 "HUNTER-GATHERER MOBILITY","RANGE EXPANSION","DISPERSAL","GEOGRAPHIC EXPANSION","SEASONAL MOBILITY","TRANS-EURASIA CULTURAL EXCHANGE","TRANSCONTINENTAL CULTURE EXCHANGE",
                 "EMIGRATION AND IMMIGRATION","ANATOMICALLY MODERN HUMANS' DISPERSALS","DISPERSALS","HOMININ DISPERSALS","HUMAN DISPERSALS","HUMAN MIGRATION","SOUTH AMERICA PEOPLING","COASTAL SPREAD",
                 "PEOPLING OF THE AMERICAS","MIGRATION","MOBILITY","POPULATION DYNAMICS","EARLY THULE EXPANSION","MOBILITY STRATEGIES"),
    
    Social = c("SOCIAL","SOCIAL INFORMATION","HUMAN COOPERATION","SOCIOCULTURAL","SOCIALLY",
                "SOCIO_CULTURAL","SOCIAL ACTION","SOCIAL BOUNDARIES","SOCIAL CHANGE","HUMAN SOCIAL",
                "SOCIAL STEREOTYPES","SOCIO-COGNITIVE CONSTRUCT","SOCIO-CULTURAL EVOLUTION","HUMAN SOCIAL BEHAVIOUR","SOCIOLOGY",
                "INTERGROUP","INTER-GROUP RELATIONSHIPS",	"SOCIAL NETWORK MAINTENANCE","SOCIAL INTERACTION",
                "SOCIAL IDENTIFICATION","SOCIAL INFLUENCE",
                "SOCIAL ROLE","SOCIAL VOLCANOLOGY",
                "PLATFORMS OF SOCIETAL DYNAMICS",	
                
                "MARRIAGE","SOCIAL NETS OF FAMILY",
                
                "GENDER RELATIONS","GENDER","WOMEN","MATRIARCHY","MATRILINEAL","MATRILINY","MATRILOCALITY","PATERNAL CARE"),
    
    Society = c("HUMAN IMPACTS","SOCIETY","SOCIETAL","SOCIETIES","PUEBLO SOCIETIES","PUEBLO SOCIETY","ANCIENT SOCIETIES","SOCIAL ORGANIZATION","COMMUNITY STRUCTURE",
               "PREHISTORIC SOCIETIES","SOCIETAL COMPLEXITY","COMPLEX SOCIETIES","SEDENTARY SOCIETIES","HUMAN SOCIETIES","CIVILIZATION",	"CIVILIZATIONS","IDEOLOGY",
               "MULTIETHNIC SOCIETIES","RACE","RACE DIFFERENCES","TRANSEGALITARIAN SOCIETIES"),
    
    Ethics_Morality = c("ANTHROPOLOGY OF ETHICS","PUNISHMENT","SOCIAL VALUES","NORMS","MORAL EMOTIONS","MORAL EVIL","MORAL REASONING","MORALITY","MORAL SENSITIVITY","PARTNERSHIP MORALITY"),
    
    Socio_political = c("SOCIOPOLITICAL","SOCIAL POLICY","SOCIOPOLITICAL COMPLEXITY","POLITICS","BIOPOLITICS","POLITICAL COMPLEXITY","POLITICAL AUTONOMY","POLITICAL","POLITICAL EVOLUTION","SOCIOPOLITICAL EVOLUTION","SOCIAL EVOLUTION","SOCIO-POLITICAL COMPLEXITY"),
    
    Economics = c("ECONOMIC HISTORY","SOCIOECONOMIC","EVOLUTIONARY ECONOMICS","ECONOMICS","SOCIO_ECONOMIC"),
    
    In_equality_Prestige = c("EGALITARIAN SOCIETIES","ALTRUISM","EQUALITY","POWER","BIG MEN","CHIEFDOM","LEADERS","PRESTIGE","SOCIAL HIERARCHY","EMERGENCE OF LEADERSHIP","SOCIAL STRUCTURE","ELITE EXCHANGE","WEALTH INEQUALITY","CHIEFDOMS","KINSHIP",
                             "INEQUALITY","ELITES","WEALTH-BASED INEQUALITY","SOCIAL STRATIFICATION","CHIEFS","INCIPIENT SOCIAL HIERARCHY","MONUMENTAL ARCHITECTURE","PALACE","STATE ORIGINS","PRESTIGE GOODS","SOCIAL STATUS",
                             "TERRITORIALITY","WAR","CONFLICT","VIOLENCE","WARFARE"),
    
    Religion_Ritual_Tradition = c("ORIGINS OF RITUAL","WOMEN'S SPIRITUALITY","RELIGION","MODES OF RELIGIOSITY","RITUAL MODES","RITUAL PRACTICES","BUDDHISM","COSMOLOGY","FEASTING","FOLKLORE",
                                  "FOLKTALES","RITUAL ARCHITECTURE","EVOLUTION OF RELIGION",	"GEOMYTHOLOGY","ANTHROPOLOGY OF SHAMANISM",	"SHAMANISM","MYTH",	"THEOLOGY AND SCIENCE",	
                                  "RELIGION AND COOPERATION",	"COGNITIVE SCIENCE OF RELIGION","RELIGION AND CULTURAL EVOLUTION", "RELIGION AND SIGNALS",	"RELIGIOUS","RITUALS","RITUAL",
                                  "MAGIC","ORAL HISTORY","ORAL TRADITION","THEOLOGICAL ANTHROPOLOGY","AFRO-BRAZILIAN RELIGION",
                                  
                                  "MORTUARY","MORTUARY RITUAL","FLOWER BURIAL","BURIAL TRADITIONS","BURIAL CUSTOMS","GRAVESTONE","GRAVESTONES"),
    
    # settlement
    Sites_Settlement = c("BURIAL SITE","KILL SITE","HUMAN SETTLEMENT DISTRIBUTION","HUMAN SETTLEMENT INTENSITY",
                   "ROCKFALL","HOMINID SITE","PALEOLITHIC SITE","PREHISTORIC HUMAN SETTLEMENT","PLEISTOCENE SITE",
                   "EBA URBANISM","ARCHAEOLOGICAL SITE","ARCHAEOLOGICAL SITE DISTRIBUTIONS",
                   "HUMAN SETTLEMENTS",
                   "HOUSING",	"SETTLEMENTS","VILLAGES","HOUSEHOLD",
                   "EARLY HUMAN OCCUPATION","HUMAN OCCUPATION" ,
                   "METAPOPULATION","SETTLEMENT DYNAMICS","SETTLEMENT EVOLUTION","SETTLEMENT MIGRATE",
                   "SETTLEMENTS DYNAMICS","TERRITORIALITY","SETTLEMENT-PATTERNS" ,
                   "LAND USE","LANDSCAPE EVOLUTION","LANDSCAPE HISTORY","LANDSCAPES",
                   "VILLAGE EMERGENCE", "PALEOLITHIC RESIDENTIAL CAMPS","HOUSEHOLD ARCHAEOLOGY", "VILLAGE","ARCHAEOLOGICAL SITES","HUMAN SETTLEMENT",
                   "SITE","SETTLEMENT PATTERN","SETTLEMENT PATTERNS","OCCUPATIONAL PATTERNS","OCCUPATION",
                   "SETTLEMENT","SEDENTISM","SITE FORMATION PROCESSES", "OPEN-AIR SITE", "ACHEULEAN SITE"),
    
    Architecture = c("RITUAL ARCHITECTURE", "MONUMENTAL ARCHITECTURE","PALACE","ARCHITECTURE"),
    
    Health_Medicine = c("PALEOPARASITOLOGY","TRADITIONAL CHINESE MEDICINE","HEALTH","MEDICAL ANTHROPOLOGY","TRADITIONAL MEDICINE","ANCIENT DISEASES",
                        "PHARMACOPOEIA")
    

    

 
    
 
    
  )
  
  
  # save categories with keywords as csv
  # readr::write_csv(plyr::ldply(meta_categories, data.frame),
  #                  file = file.path("2_data", "thesaurus_DE_TI_AB.csv"))
  # readr::write_csv(data.frame(category = unique(names(meta_categories))),
  #                  file = file.path("2_data", "thesaurus_categories.csv"))
  
  # 
  # unclear
  unclear <- c("ORGANIZATION",
               "EMERGENCE",
               "ORIGIN",
               "MODERNITY","ANATOMICALLY MODERN",
               "DYNAMICS","CULTURAL DYNAMICS",
               "DECREASE","DISAPPEARANCE",
               
               
               "REMOTE SENSING","REMOTE SENSING TECHNOLOGY",
               "2D \\& 3D MAPPING",
               
               "EXPERIMENTAL ARCHAEOLOGY",
               
               
               
               "LEROI-GOURHAN",
               
               
               "ETHNOLOGY",
               
               "INTERPOPULATION VARIATION")
  
  # new_joined_ID_DE_AU <- NA
  # for(i in 1:(joined_ID_DE$AU)){
  #   splitted_short_ref <- strsplit(joined_ID_DE$AU, ",")[[i]]
  #   
  #   FirstAuthorSplit <- strsplit(splitted_short_ref[1], " ")[[1]]
  #   
  #   if(nchar(FirstAuthorSplit[length(FirstAuthorSplit)]) > 1){
  #     new_joined_ID_DE_AU[i] <- paste0(gsub('.{1}$', '', splitted_short_ref[1]), ",",
  #                                      splitted_short_ref[2], ",",
  #                                      splitted_short_ref[3], ",")
  #   } else {
  #     new_joined_ID_DE_AU[i] <- joined_ID_DE$AU[i]
  #   }
  #   
  # }
  # joined_ID_DE$AU <- new_joined_ID_DE_AU
  
  not_in_thesaurus <- colnames(joined_ID_DE)[which(!(colnames(joined_ID_DE) %in% unlist(meta_categories)))]
  # writeLines(paste(not_in_thesaurus, collapse = ","), file.path("3_output", "keywords_not_in_thesaurus_DE_TI_AB.txt"))
  
  
  thesauriert <- data.frame(AU = rownames(joined_ID_DE))
  
  for (meta_category_index in unique(names(meta_categories))) {
    
    current_keywords <- meta_categories[[meta_category_index]]
    
    if ("TRUE" %in% names(table(current_keywords %in% colnames(joined_ID_DE)))){
      
      if(table(current_keywords %in% colnames(joined_ID_DE))[["TRUE"]] > 1){
        summed_rows <- rowSums(joined_ID_DE[,current_keywords[which(current_keywords %in% colnames(joined_ID_DE))]])
        
        tmp_df <- data.frame(AU = names(summed_rows),
                             meta_category = summed_rows)
      } else {
        
        tmp_df <- data.frame(AU = rownames(joined_ID_DE),
                             meta_category = joined_ID_DE[,current_keywords[which(current_keywords %in% colnames(joined_ID_DE))]])
        
      }
      
      names(tmp_df)[2] <- meta_category_index
      
      thesauriert <- dplyr::left_join(thesauriert, tmp_df, by = "AU")
    }
      
  }
    
  return(thesauriert)
  # summary_cols <- 
  #   data.frame(meta_category = colnames(thesauriert[,2:ncol(thesauriert)]),
  #              count = colSums(thesauriert[,2:ncol(thesauriert)]))
  # ggplot(data = arrange(summary_cols, desc(count)),
  #        aes(x = meta_category,
  #            y = count)) +
  # geom_col() +
  #   coord_flip()
  
  # thesauriert_joined <- left_join(joined_ID_DE[,-(which(colnames(joined_ID_DE) == as.character(unlist(meta_categories))))],
  #                                 thesauriert,
  #                                 by = "AU")
  
  # thesauriert_joined <- left_join(joined_ID_DE[,c(unclear, "AU")], 
  #                                 thesauriert, 
  #                                 by = "AU")
  
  # thesauriert_joined <- subset(thesauriert, "Cultural_Evolution" >= 1)
  # return(thesauriert_joined)
  # nrow(thesauriert_joined)

}
